/*
 * Auth.
 */

// Token.
export const LOADED_TOKEN = 'LOADED_TOKEN';
export const RECIEVED_TOKEN = 'RECIEVED_TOKEN';

// Login.
export const SHOW_LOGIN = 'SHOW_LOGIN';
export const REDIRECT_LOGIN = 'REDIRECT_LOGIN';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

// Logout.
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

/*
 * Cases.
 */
// Fetch all.
export const FETCH_CASES = 'FETCH_CASES';
export const FETCH_CASES_PENDING = 'FETCH_CASES_PENDING';
export const FETCH_CASES_REJECTED = 'FETCH_CASES_REJECTED';
export const FETCH_CASES_FULFILLED = 'FETCH_CASES_FULFILLED';


/*
 * Orders.
 */

// Create order.
export const REQUEST_CREATE_ORDER = 'REQUEST_CREATE_ORDER';
export const CANCEL_CREATE_ORDER = 'CANCEL_CREATE_ORDER';
export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_PENDING = 'CREATE_ORDER_PENDING';
export const CREATE_ORDER_REJECTED = 'CREATE_ORDER_REJECTED';
export const CREATE_ORDER_FULFILLED = 'CREATE_ORDER_FULFILLED';

// Delete order.
export const REQUEST_DELETE_ORDER = 'REQUEST_DELETE_ORDER';
export const CANCEL_DELETE_ORDER = 'CANCEL_DELETE_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';
export const DELETE_ORDER_PENDING = 'DELETE_ORDER_PENDING';
export const DELETE_ORDER_REJECTED = 'DELETE_ORDER_REJECTED';
export const DELETE_ORDER_FULFILLED = 'DELETE_ORDER_FULFILLED';

// Fetch all.
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_PENDING = 'FETCH_ORDERS_PENDING';
export const FETCH_ORDERS_REJECTED = 'FETCH_ORDERS_REJECTED';
export const FETCH_ORDERS_FULFILLED = 'FETCH_ORDERS_FULFILLED';

// Fetch single.
export const FETCH_ORDER = 'FETCH_ORDER';
export const FETCH_ORDER_PENDING = 'FETCH_ORDER_PENDING';
export const FETCH_ORDER_REJECTED = 'FETCH_ORDER_REJECTED';
export const FETCH_ORDER_FULFILLED = 'FETCH_ORDER_FULFILLED';
