/*
 * Auth.
 */

// Update Shipping
export const REQUEST_UPDATE_SHIPPED_DATE = 'REQUEST_UPDATE_SHIPPED_DATE';
export const CANCEL_UPDATE_SHIPPED_DATE = 'CANCEL_UPDATE_SHIPPED_DATE';
export const UPDATE_SHIPPED_DATE = 'UPDATE_SHIPPED_DATE';
export const UPDATE_SHIPPED_DATE_PENDING = 'UPDATE_SHIPPED_DATE_PENDING';
export const UPDATE_SHIPPED_DATE_REJECTED = 'UPDATE_SHIPPED_DATE_REJECTED';
export const UPDATE_SHIPPED_DATE_FULFILLED = 'UPDATE_SHIPPED_DATE_FULFILLED';

